// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDy7cqtcw4eXq6OYaeiZ9oxOnz5kWO-y4',
    appId: '1:558258187506:web:b23f280755467efcc3346b',
    messagingSenderId: '558258187506',
    projectId: 'lawer-finder-dcbf7',
    authDomain: 'lawer-finder-dcbf7.firebaseapp.com',
    storageBucket: 'lawer-finder-dcbf7.appspot.com',
    measurementId: 'G-BFGSTQCBVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYlHJqfkt0E12wbzsiVfu72TZ0iXpcjiY',
    appId: '1:558258187506:android:a981b3c310dd6135c3346b',
    messagingSenderId: '558258187506',
    projectId: 'lawer-finder-dcbf7',
    storageBucket: 'lawer-finder-dcbf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD53Ip6eJANiHO4A1KH5Uywn7ZbVQrUdCU',
    appId: '1:558258187506:ios:0ad195373cafd081c3346b',
    messagingSenderId: '558258187506',
    projectId: 'lawer-finder-dcbf7',
    storageBucket: 'lawer-finder-dcbf7.appspot.com',
    iosBundleId: 'com.example.lawerFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD53Ip6eJANiHO4A1KH5Uywn7ZbVQrUdCU',
    appId: '1:558258187506:ios:e6d3955f19f1adbcc3346b',
    messagingSenderId: '558258187506',
    projectId: 'lawer-finder-dcbf7',
    storageBucket: 'lawer-finder-dcbf7.appspot.com',
    iosBundleId: 'com.example.lawerFinder.RunnerTests',
  );
}
